<?php
if(Mage::getSingleton('customer/session')->isLoggedIn()):
  $name = Mage::getSingleton('customer/session')->getCustomer()->getName();
endif;
?>

<style media="screen">

  .negrito{
    font-weight:bold;
    width: 60%;
    line-height: 3em;
  }

</style>
<div class="box">
  <div class="box-content">
    <form class='negrito' method="post" action="<?php echo Mage::getUrl('newpage/index/cadastro');?>" >
      Nome: <input  type="text" name="name"><br>
      Sobrenome: <input type="text" name="lastname"><br>
      Descrição: <textarea name="texto" rows="8" cols="80"></textarea><br>
      <input type="submit" name="botao" value="Enviar">
    </form>

  </div>
</div>
