<?php
if(Mage::getSingleton('customer/session')->isLoggedIn()):
  $name = Mage::getSingleton('customer/session')->getCustomer()->getName();
endif;
?>
<style media="screen">
conteudo{

}
table,th,td{
  margin-top: 1.5em;
  border: 1px solid black;
  width: 60%;
  padding-left: 5px;
}
th{
  font-weight: bold;
}
th,td{
  width: 50%;
}
</style>
<div class="box">
  <div class="box-content">
    <div class="conteudo">
    <?php $pessoas = $this->getDataNewpage() ?>
    <button type="submit" name="button" onclick="functionCriar()">Criar</button>

    <table>
      <tr>
        <th>Nome</th>
        <th>Sobrenome</th>
      </tr>
      <?php foreach ($pessoas as $pessoa):?>
        <tr>
          <td><?php echo $pessoa->getData('name'); ?></td>
          <td><?php echo $pessoa->getData('lastname'); ?></td>
        </tr>
      <?php endforeach;?>
    </table>
  </div>
  </div>
</div>

<script type="text/javascript">
  function functionCriar(){
    window.location.href = "/magento/newpage/index/create";
  }
</script>
