<?php
if (Mage::getSingleton('customer/session')->isLoggedIn()):
    $name = Mage::getSingleton('customer/session')->getCustomer()->getName();
endif;
?>


<div class="box">
    <div class="box-content">
        <form id="my-custom-form" method="post" action="">
            <label for="name" class="required">Nome: </label>
            <div class="input-box">
                <input type="text" name="name" class="required required-entry validate-alpha"><br>
            </div>
            <label for="emil" class="required">Email: </label>
            <div class="input-box">
                <input type="text" name="email" class="required required-entry validate-email"><br>
            </div>
            <label for="phone" class="required required-entry ">Telefone: </label>
            <div class="input-box">
                <input type="text" name="phone"
                       class="input-text  required-entry validate-length maximum-length-10 minimum-length-10 validate-digits"><br>
            </div>
            Genero:
            <input type="radio" name="gender" value="Masculino" checked> Masculino
            <input type="radio" name="gender" value="Femenino"> Femenino<br>
            <button type="submit">Enviar</button>
        </form>

    </div>
</div>
<script type="text/javascript">
    //< ![CDATA[
    var customForm = new VarienForm('my-custom-form');
    //]]>
</script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script type="text/javascript">
    var request;
    jQuery.noConflict();
    jQuery('#my-custom-form').submit(function (event) {
        if (jQuery(this).find(".validation-failed").length != 0)
            return;
        event.preventDefault();

        // Abort any pending request
        if (request) {
            request.abort();
        }
        // setup some local variables
        var form = jQuery(this);

        // Let's select and cache all the fields
        var inputs = form.find("input, select, button, textarea");

        // Serialize the data in the form
        var serializedData = form.serialize();

        // Let's disable the inputs for the duration of the Ajax request.
        // Note: we disable elements AFTER the form data has been serialized.
        // Disabled form elements will not be serialized.
        inputs.prop("disabled", true);

        // Fire off the request to /form.php
        request = jQuery.ajax({
            url: "<?php echo Mage::getUrl('learning/index/cadastro');?>",
            type: "post",
            data: serializedData
        });

        // Callback handler that will be called on success
        request.done(function (response, textStatus, jqXHR) {
            window.location.replace("<?php echo Mage::getUrl('learning/index');?>");
        });

        // Callback handler that will be called on failure
        request.fail(function (jqXHR, textStatus, errorThrown) {
            // Log the error to the console
            alert("Erro ao cadastrar");
            window.location.replace("<?php echo Mage::getUrl('learning/index/create');?>");
        });


    });
</script>
