<?php
if (Mage::getSingleton('customer/session')->isLoggedIn()):
    $name = Mage::getSingleton('customer/session')->getCustomer()->getName();
endif;
?>
<style media="screen">
    conteudo {

    }

    table, th, td {
        margin-top: 1.5em;
        border: 1px solid black;
        width: 60%;
        padding-left: 5px;
    }

    th {
        font-weight: bold;
    }

    th, td {
        width: 50%;
    }

    .myclass {
        -webkit-box-shadow: 0 0 0;
        -moz-box-shadow: 0 0 0;
        box-shadow: 0 0 0;
    }

</style>
<div class="box">
    <div class="box-content">
        <div class="conteudo">
            <?php $contatos = $this->getDataLearning() ?>
            <button type="submit" name="button" onclick="functionCriar()">Criar</button>
            <button type="submit" name="button" id="test_me"
            ">POP</button>

            <table>
                <tr>
                    <th>Nome</th>
                    <th>email</th>
                </tr>
                <?php foreach ($contatos as $contato): ?>
                    <tr>
                        <td><?php echo $contato->getData('nome'); ?></td>
                        <td><?php echo $contato->getData('email'); ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>


<script type="text/javascript">

    function functionCriar() {
        window.location.href = "/magento/learning/index/create";
    }

    jQuery.noConflict();

    jQuery.fancybox.open('<div class="message"><h2>Mensagem</h2><img src="<?php echo $this->getSkinUrl('images/pop.png')?>"></div>');


</script>


